import type { Achievement } from '../types/achievements';

export const ACHIEVEMENTS: Achievement[] = [
  // ── Exploration ──
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Visit the portfolio for the first time',
    icon: '👋',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'curious-mind',
    name: 'Curious Mind',
    description: 'Visit every main section of the portfolio',
    icon: '🧠',
    xp: 20,
    category: 'exploration',
  },
  {
    id: 'detail-oriented',
    name: 'Detail Oriented',
    description: 'Read the About section',
    icon: '🔍',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'tech-savvy',
    name: 'Tech Savvy',
    description: 'Check out the Skills section',
    icon: '💻',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'project-hunter',
    name: 'Project Hunter',
    description: 'View all featured projects',
    icon: '🏹',
    xp: 15,
    category: 'exploration',
  },
  {
    id: 'stats-enthusiast',
    name: 'Stats Enthusiast',
    description: 'Check out the GitHub statistics section',
    icon: '📊',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'hobby-explorer',
    name: 'Hobby Explorer',
    description: 'Explore the personal hobbies section',
    icon: '🎯',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'resume-reviewer',
    name: 'Resume Reviewer',
    description: 'View or download the resume',
    icon: '📄',
    xp: 10,
    category: 'exploration',
  },
  {
    id: 'replay-watcher',
    name: 'Replay Watcher',
    description: 'Watch the GitHub Replay animation',
    icon: '🎬',
    xp: 10,
    category: 'exploration',
  },
  // ── Special ──
  {
    id: 'speed-reader',
    name: 'Speed Reader',
    description: 'Scroll to the bottom within 30 seconds',
    icon: '⚡',
    xp: 15,
    category: 'special',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Visit between midnight and 5 AM',
    icon: '🦉',
    xp: 10,
    category: 'special',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Visit between 5 AM and 8 AM',
    icon: '🐦',
    xp: 10,
    category: 'special',
  },
  {
    id: 'committed-visitor',
    name: 'Committed Visitor',
    description: 'Stay on the portfolio for 2+ minutes',
    icon: '⏱️',
    xp: 10,
    category: 'special',
  },
  {
    id: 'scroll-master',
    name: 'Scroll Master',
    description: 'Scroll over 10,000 pixels total',
    icon: '📜',
    xp: 15,
    category: 'special',
  },
  {
    id: 'social-butterfly',
    name: 'Social Butterfly',
    description: 'Click on any social or external link',
    icon: '🦋',
    xp: 10,
    category: 'special',
  },
  // ── Secret ──
  {
    id: 'konami-master',
    name: 'Konami Master',
    description: 'Enter the legendary Konami code',
    icon: '🎮',
    xp: 25,
    category: 'secret',
  },
  {
    id: 'command-pro',
    name: 'Command Pro',
    description: 'Open the command palette',
    icon: '⌨️',
    xp: 10,
    category: 'special',
  },
  // ── Meta ──
  {
    id: 'achievement-hunter',
    name: 'Achievement Hunter',
    description: 'Unlock 10 or more achievements',
    icon: '🏆',
    xp: 25,
    category: 'meta',
  },
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Unlock every single achievement',
    icon: '👑',
    xp: 50,
    category: 'meta',
  },
];
