import type { VisitorAchievement } from '../types/achievements';

export const ACHIEVEMENTS: VisitorAchievement[] = [
  {
    id: 'first-steps',
    title: 'First Steps',
    description: 'Visit the portfolio',
    icon: '👋',
    unlocked: false,
    trigger: 'auto',
    rarity: 'common',
    xp: 10,
  },
  {
    id: 'curious-mind',
    title: 'Curious Mind',
    description: 'Scroll through all sections',
    icon: '🔍',
    unlocked: false,
    trigger: 'scroll',
    rarity: 'common',
    xp: 25,
  },
  {
    id: 'detail-oriented',
    title: 'Detail Oriented',
    description: 'View the About section',
    icon: '📖',
    unlocked: false,
    trigger: 'scroll',
    triggerCondition: 'about',
    rarity: 'common',
    xp: 15,
  },
  {
    id: 'star-gazer',
    title: 'Star Gazer',
    description: 'Click the GitHub link',
    icon: '⭐',
    unlocked: false,
    trigger: 'click',
    triggerCondition: 'github',
    rarity: 'common',
    xp: 20,
  },
  {
    id: 'socially-active',
    title: 'Socially Active',
    description: 'Click the LinkedIn link',
    icon: '💼',
    unlocked: false,
    trigger: 'click',
    triggerCondition: 'linkedin',
    rarity: 'common',
    xp: 20,
  },
  {
    id: 'contact-initiator',
    title: 'Contact Initiator',
    description: 'Click the email link',
    icon: '✉️',
    unlocked: false,
    trigger: 'click',
    triggerCondition: 'email',
    rarity: 'common',
    xp: 20,
  },
  {
    id: 'project-hunter',
    title: 'Project Hunter',
    description: 'View all projects',
    icon: '🚀',
    unlocked: false,
    trigger: 'scroll',
    triggerCondition: 'projects',
    rarity: 'rare',
    xp: 35,
  },
  {
    id: 'committed-visitor',
    title: 'Committed Visitor',
    description: 'Spend 2+ minutes on the page',
    icon: '⏱️',
    unlocked: false,
    trigger: 'time',
    triggerCondition: '120000',
    rarity: 'rare',
    xp: 40,
  },
  {
    id: 'tech-savvy',
    title: 'Tech Savvy',
    description: 'View the Skills section',
    icon: '⚡',
    unlocked: false,
    trigger: 'scroll',
    triggerCondition: 'skills',
    rarity: 'common',
    xp: 25,
  },
  {
    id: 'konami-master',
    title: 'Konami Master',
    description: 'Enter the Konami code',
    icon: '🎮',
    unlocked: false,
    trigger: 'konami',
    rarity: 'legendary',
    xp: 100,
  },
  {
    id: 'command-pro',
    title: 'Command Pro',
    description: 'Use the command palette (⌘K)',
    icon: '⌨️',
    unlocked: false,
    trigger: 'click',
    triggerCondition: 'command-palette',
    rarity: 'rare',
    xp: 30,
  },
  {
    id: 'night-owl',
    title: 'Night Owl',
    description: 'Visit between midnight and 5am',
    icon: '🦉',
    unlocked: false,
    trigger: 'time',
    triggerCondition: 'night',
    rarity: 'epic',
    xp: 50,
  },
  {
    id: 'speed-reader',
    title: 'Speed Reader',
    description: 'Scroll to the bottom in under 30 seconds',
    icon: '⚡',
    unlocked: false,
    trigger: 'scroll',
    triggerCondition: 'speed',
    rarity: 'rare',
    xp: 40,
  },
  {
    id: 'achievement-hunter',
    title: 'Achievement Hunter',
    description: 'Unlock 10 or more achievements',
    icon: '🏆',
    unlocked: false,
    trigger: 'auto',
    rarity: 'epic',
    xp: 75,
  },
  {
    id: 'completionist',
    title: 'Completionist',
    description: 'Unlock all achievements',
    icon: '👑',
    unlocked: false,
    trigger: 'auto',
    rarity: 'legendary',
    xp: 150,
  },
];

export function getTotalPossibleXP(): number {
  return ACHIEVEMENTS.reduce((sum, a) => sum + a.xp, 0);
}
