import type { Achievement, AchievementRarity } from '../types/achievements';

/** Rarity display order (highest → lowest) */
export const RARITY_ORDER: AchievementRarity[] = [
  'legendary',
  'epic',
  'rare',
  'uncommon',
  'common',
];

export const RARITY_LABELS: Record<AchievementRarity, string> = {
  legendary: 'LEGENDARY',
  epic: 'EPIC',
  rare: 'RARE',
  uncommon: 'UNCOMMON',
  common: 'COMMON',
};

export const ACHIEVEMENTS: Achievement[] = [
  // ── COMMON (8) — easy exploration tasks ──
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Welcome to my portfolio! Thanks for visiting.',
    icon: '👋',
    xp: 10,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'curious-mind',
    name: 'Curious Mind',
    description: 'Explored all main sections of the portfolio',
    icon: '🧠',
    xp: 25,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'detail-oriented',
    name: 'Detail Oriented',
    description: 'Read through the About section',
    icon: '🔍',
    xp: 10,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'tech-savvy',
    name: 'Tech Savvy',
    description: 'Explored the technical skills section',
    icon: '💻',
    xp: 15,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'stats-enthusiast',
    name: 'Stats Enthusiast',
    description: 'Checked out my GitHub statistics',
    icon: '📊',
    xp: 15,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'hobby-explorer',
    name: 'Hobby Enthusiast',
    description: 'Explored my personal hobbies section',
    icon: '🎯',
    xp: 15,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'resume-reviewer',
    name: 'Resume Reviewer',
    description: 'Viewed or downloaded the resume',
    icon: '📄',
    xp: 10,
    category: 'exploration',
    rarity: 'common',
  },
  {
    id: 'replay-watcher',
    name: 'Replay Watcher',
    description: 'Watched the GitHub Replay animation',
    icon: '🎬',
    xp: 10,
    category: 'exploration',
    rarity: 'common',
  },

  // ── UNCOMMON (4) — requires specific behaviour ──
  {
    id: 'social-butterfly',
    name: 'Social Butterfly',
    description: 'Clicked on a social or external link',
    icon: '🦋',
    xp: 15,
    category: 'special',
    rarity: 'uncommon',
  },
  {
    id: 'command-pro',
    name: 'Command Pro',
    description: 'Opened the command palette (⌘K)',
    icon: '⌨️',
    xp: 15,
    category: 'special',
    rarity: 'uncommon',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Visited the portfolio between midnight and 5 AM',
    icon: '🦉',
    xp: 15,
    category: 'special',
    rarity: 'uncommon',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Visited the portfolio between 5 AM and 8 AM',
    icon: '🐦',
    xp: 15,
    category: 'special',
    rarity: 'uncommon',
  },

  // ── RARE (4) — requires effort or time ──
  {
    id: 'committed-visitor',
    name: 'Committed Visitor',
    description: 'Spent over 2 minutes exploring the portfolio',
    icon: '⏱️',
    xp: 40,
    category: 'special',
    rarity: 'rare',
  },
  {
    id: 'scroll-master',
    name: 'Scroll Master',
    description: 'Scrolled over 10,000 pixels across the portfolio',
    icon: '📜',
    xp: 25,
    category: 'special',
    rarity: 'rare',
  },
  {
    id: 'project-hunter',
    name: 'Project Hunter',
    description: 'Viewed every single featured project',
    icon: '🏹',
    xp: 25,
    category: 'exploration',
    rarity: 'rare',
  },
  {
    id: 'speed-reader',
    name: 'Speed Reader',
    description: 'Reached the bottom of the page within 30 seconds',
    icon: '⚡',
    xp: 30,
    category: 'special',
    rarity: 'rare',
  },

  // ── EPIC (2) — very hard ──
  {
    id: 'konami-master',
    name: 'Konami Master',
    description: 'Entered the legendary Konami code',
    icon: '🎮',
    xp: 50,
    category: 'secret',
    rarity: 'epic',
  },
  {
    id: 'achievement-hunter',
    name: 'Achievement Hunter',
    description: 'Unlocked 10 or more achievements',
    icon: '🏆',
    xp: 50,
    category: 'meta',
    rarity: 'epic',
  },

  // ── LEGENDARY (1) — ultimate ──
  {
    id: 'completionist',
    name: 'Completionist',
    description: 'Unlocked every single achievement — true dedication!',
    icon: '👑',
    xp: 100,
    category: 'meta',
    rarity: 'legendary',
  },
];
